export const AUTH_UPSTREAM_UNAVAILABLE = 'AUTH_UPSTREAM_UNAVAILABLE'
export const ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND'
export const PASSWORD_RESET_EMAIL_DELIVERY_FAILED = 'PASSWORD_RESET_EMAIL_DELIVERY_FAILED'
export const PASSWORD_ALREADY_IN_USE = 'PASSWORD_ALREADY_IN_USE'
